import type { Lang } from '@/lib/i18n/translations'

/** Префиксы для ротирующейся строки «в [городе] крупнейшая выставка…» */
export const LANDING_ROTATING_CITY_PREFIXES: Record<Lang, readonly string[]> = {
  uz: [
    'Toshkentdagi',
    'Samarqanddagi',
    'Buxorodagi',
    'Urganchdagi',
    'Nukusdagi',
    'Navoiydagi',
    "Far'gonadagi",
    'Andijondagi',
    'Namangandagi',
    'Jizzaxdagi',
    'Qarshidagi',
    'Termizdagi',
  ],
  ru: [
    'В Ташкенте',
    'В Самарканде',
    'В Бухаре',
    'В Ургенче',
    'В Нукусе',
    'В Навои',
    'В Фергане',
    'В Андижане',
    'В Намангане',
    'В Джизаке',
    'В Карши',
    'В Термезе',
  ],
  en: [
    'In Tashkent',
    'In Samarkand',
    'In Bukhara',
    'In Urgench',
    'In Nukus',
    'In Navoi',
    'In Fergana',
    'In Andijan',
    'In Namangan',
    'In Jizzakh',
    'In Karshi',
    'In Termez',
  ],
}

/** Короткие названия городов для блока «города выставок» на лендинге */
export const LANDING_EXHIBITION_CITY_LABELS: Record<Lang, readonly string[]> = {
  ru: [
    'Ташкент',
    'Самарканд',
    'Бухара',
    'Ургенч',
    'Нукус',
    'Навои',
    'Фергана',
    'Андижан',
    'Наманган',
    'Джизак',
    'Карши',
    'Термез',
  ],
  en: [
    'Tashkent',
    'Samarkand',
    'Bukhara',
    'Urgench',
    'Nukus',
    'Navoi',
    'Fergana',
    'Andijan',
    'Namangan',
    'Jizzakh',
    'Karshi',
    'Termez',
  ],
  uz: [
    'Toshkent',
    'Samarqand',
    'Buxoro',
    'Urganch',
    'Nukus',
    'Navoiy',
    "Farg'ona",
    'Andijon',
    'Namangan',
    'Jizzax',
    'Qarshi',
    'Termiz',
  ],
}
